#!/bin/bash

if [[ -n "$1" && "$1" == *:*:*:* ]]; then
    IFS=':' read -r proxy_ip proxy_port proxy_user proxy_pass <<< "$1"
    shift
    exec curl --proxy "http://${proxy_user}:${proxy_pass}@${proxy_ip}:${proxy_port}" "$@"
else
    exec curl "$@"
fi

